# Generated by Django 4.0.2 on 2022-02-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название маршрута')),
                ('startpoint', models.TextField(verbose_name='Начальная точка маршрута')),
                ('endpoint', models.TextField(verbose_name='Конечная точка маршрута')),
                ('waypoints', models.TextField(verbose_name='Точки маршрутов')),
                ('author', models.TextField(verbose_name='Автор маршрута')),
            ],
        ),
    ]
