# Generated by Django 4.0.2 on 2022-02-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='endpoint',
            field=models.TextField(null=True, verbose_name='Конечная точка маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='startpoint',
            field=models.TextField(null=True, verbose_name='Начальная точка маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=models.TextField(null=True, verbose_name='Точки маршрутов'),
        ),
    ]
