# Generated by Django 4.0.2 on 2022-02-24 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='waypoints.waypoint')),
                ('startpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startpoint', to='waypoints.waypoint')),
                ('waypoints', models.ManyToManyField(to='waypoints.WayPoint')),
            ],
        ),
    ]
