# Generated by Django 4.0.2 on 2022-02-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0002_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=models.ManyToManyField(null=True, to='waypoints.WayPoint'),
        ),
    ]
