# Generated by Django 4.0.2 on 2022-02-25 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0003_alter_route_waypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='waypoints.waypoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='startpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startpoint', to='waypoints.waypoint'),
        ),
    ]
